version: '3.8'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: ../../../..
      dockerfile: src/Api/WebApi/RentACar.Api.WebApi/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgreSQL=Host=postgres;Port=5432;Database=rentacardb;Username=RentACarRootUser;Password=lh9P0U5ClWryCmD2LKdkvhL2j;
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: rentacar_postgres
    environment:
      POSTGRES_USER: RentACarRootUser
      POSTGRES_PASSWORD: lh9P0U5ClWryCmD2LKdkvhL2j
      POSTGRES_DB: rentacardb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
